name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Chromium
        run: sudo apt-get update && sudo apt-get install -y chromium-browser

      - name: Run tests
        env:
          CHROME_BIN: /usr/bin/chromium-browser
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Build project
        run: npm run build
